config/routes.rb
Awesometrain::Application.routes.draw do
  resources :trainings

  devise_for :users
  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  root :to => 'pages#home'

  

end

app/models/training.rb
class Training < ActiveRecord::Base
	validates :description, presence: true

	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable,
         :rememberable, :trackable, :validatable

  has_many :trainings, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :current_password, :password, :password_confirmation) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_training, only: [:show, :edit, :update, :destroy]
  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = current_user.trainings.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = current_user.trainings.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render action: 'show', status: :created, location: @training }
      else
        format.html { render action: 'new' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/_footer.html.erb
<div class=footer>
	<div class="row-fluid">
		<div class="span4">	
	  	<small>
		Designed by <%= link_to "Jessica Lin", "http://jerseejess.com" %>
			</small>
		</div>
		<div class="span8">	
			<div class="span-footer">
				<small>
				<%= link_to "Back to Top", root_path %>
				</small>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <%= link_to "Awesome Train", root_path, class: "brand" %>

      <div class="nav-collapse pull-right">
        <ul class="nav">
          <li><%= link_to 'About',  about_path %></li>
          <li><%= link_to 'Contact',  contact_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %> 
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Awesome Train</title>
	  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
		  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		  <%= csrf_meta_tags %>
		  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		</head>
		<body>

			<%= render 'layouts/header' %>
			<div class="container">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
				<%= yield %>
			</div>
				<%= render 'layouts/footer' %>
		</body>
</html>

app/views/pages/about.html.erb
<div class="row">
	<div class="span6 offset1">
		<h1>About</h1>
			<p>
				It is really hard to build good trainings. Awesome Train helps you make them awesome.
			</p>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="row">
	<div class="span6 offset1">
		<h1>Contact</h1>
			<p>
				<span id="logo"><img src="mail.png" width="16" height="16"></span>
				hello [at] awesometrain [dot] com
			<p>
	</div>
</div>

app/views/pages/create.html.erb
<div class="row">
	<div class="span4">
		<h1>Welcome to One Month Rails!</h1>
		<p>You've found the home page</p>
	</div>
	</div>
	<div class="span8"><html>
		<h2>Navigation Bar</h2>
</div>

app/views/pages/home.html.erb
<!-- Hero Unit -->

<% if user_signed_in? %>
	<h1> You're logged in!</h1>
<% else %>
	<div class="center hero-unit">
	    <h1>Welcome to Awesome Train</h1>
	    <h3>Building <span style="text-decoration: line-through;">Better</span> Awesome Trainings Easily</h3>
	    <p> <%= link_to 'Sign Up Now', new_user_registration_path, class: "btn btn-large btn-primary" %> </p>
	</div>
<% end %>

<!-- End Hero Unit -->


<!-- Begin MailChimp Signup Form -->
			
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width: 500px; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

<div class="row-fluid">
  <div class="span4 offset4">
		<div id="mc_embed_signup">
			<form action="http://skillvee.us6.list-manage.com/subscribe/post?u=bac00f58fb88266d3d3bbf70d&amp;id=79cdebb214" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				<label for="mce-EMAIL">Sign Up To Hear When We Launch!</label>
				<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Email" required>
				<div class="clear">
					<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
				</div>
			</form>
		</div>
	</div>
</div>
	
<!-- End mc_embed_signup-->

<!-- how to attach to db? -->

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
    </div>
    <div class="span4">
    <form class="form-inline">
	<h4>Sign up for more info!</h4>
  <input type="text" class="input-small" style="width: 250px" placeholder="Email">
  <button type="submit" class="btn">Sign Up</button>
</form>
    </div>
  </div>
</div>


<!-- end -->

<div class="middle-section">
	<div class="row-fluid">
		<div class="span4">
			<center><img src="mail.png" width="160" height="160"></center>
			<h4>Interactive</h4>
		</div>
		<div class="span4">
			<center><img src="chat.png" width="160" height="160"></center>
			<h4>Easy to Use</h4>
		</div>
		<div class="span4">
			<center><img src="bulb.png" width="160" height="160"></center>
			<h4>Relevant</h4>
		</div>
	</div>
</div>

app/views/trainings/_form.html.erb
<%= simple_form_for(@training, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: { rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<tr>
    <td><%= training.description %></td>
    <td><%= link_to 'Show', training %></td>
    <% if current_user == training.user %>
	    <td><%= link_to 'Edit', edit_training_path(training) %></td>
	    <td><%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</tr>

app/views/trainings/edit.html.erb
<h1>Editing training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<h1>Listing trainings</h1>

<table class="table table-striped">
  <thead>
    <tr>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trainings %>
  </tbody>
</table>

<br />

<%= link_to 'New Training', new_training_path %>

app/views/trainings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			  <%= @training.description %>
		  </p>
			<p>
			  <%= @training.user.name %>
		  </p>
		  <% if current_user == @training.user %>
			  <%= link_to 'Edit', edit_training_path(@training) %> |
		  <% end %>
			<%= link_to 'Back', trainings_path %>
		</div>
	</div>
</div>